version: 2
jobs:
  build:
    working_directory: /aws-cloud-controller-manager
    docker:
      - image: docker:19.03.2-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/aws-cloud-controller-manager.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/aws-cloud-controller-manager.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=aws-cloud-controller-manager -t jubican/aws-cloud-controller-manager:1.0.0 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/aws-cloud-controller-manager.tar jubican/aws-cloud-controller-manager
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/aws-cloud-controller-manager.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push jubican/aws-cloud-controller-manager:1.0.0
            fi
